In [2]:
!pip install numpy
import numpy as np

### exercise 1

In [4]:
np.arange(1,10+1,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(0.5,5+0.25,0.25)

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### exerise 2

In [7]:
np.zeros((10), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### exerise 3

In [10]:
np.linspace(2,12,5)

array([ 2. ,  4.5,  7. ,  9.5, 12. ])

In [11]:
np.linspace(3,9,4)

array([3., 5., 7., 9.])

### exerise 4

In [13]:
np.random.rand(2,4)

array([[0.31440595, 0.69734909, 0.76289843, 0.49036723],
       [0.64457184, 0.73610691, 0.23161156, 0.77958894]])

In [14]:
np.random.randint(10,21,(3,3))

array([[19, 17, 16],
       [12, 18, 18],
       [10, 18, 11]])

### exerise 5

If we'll randomise numbers using a fixed seed number, the result will always be the same.
The advantages of using seed numbers are that you can mimic the same results by using the same seed number.